version: '3'
services:
  frontend:
    build:
      context: ./front/
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    build:
      context: ./back/Paper.Api//Paper.Api/  # Adapte le chemin de ton backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # On monte le fichier de config
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
