version: '3'
services:
  frontend:
    build:
      context: ./front/
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    build:
      context: ./back/Paper.Api//Paper.Api/  
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KEYCLOAK_LOG_LEVEL: DEBUG
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_PROXY: edge
        KC_HOSTNAME_STRICT: false
      command:
        - start-dev
      ports:
        - "8085:8080"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
