name: CI Pipeline

on: [push, pull_request]

jobs:
  front:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run tests
        run: |
          cd front
          npm test

      - name: Build the project
        run: |
          cd front
          npm run build

  back:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Run tests
        run: |
          cd back
          npm test

      - name: Build the project
        run: |
          cd back
          npm run build

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up --build

      - name: Run integration tests
        run: |
          docker-compose exec app npm test
